#!/bin/sh

# Install flutter in runner if not exist.
install_ci_flutter(){
    if [ ! -d $FLUTTER_PATH/bin ]; then
        git clone --single-branch --branch $FLUTTER_VERSION --depth 1 https://github.com/flutter/flutter.git $FLUTTER_PATH
    else
        echo Flutter SDK already exist.
    fi

    echo "$PWD/$FLUTTER_PATH/bin" >> $GITHUB_PATH
    $FLUTTER_PATH/bin/flutter pub get
}

android_build_apk(){
    flutter build apk
    echo $PWD/build/app/outputs/flutter-apk
}

if [ "$1" = "install-ci-flutter" ]; then install_ci_flutter; exit; fi
if [ "$1" = "lint" ]; then flutter analyze; exit $?; fi
if [ "$1" = "test" ]; then flutter test; exit $?; fi
if [ "$1" = "build-apk" ]; then android_build_apk; exit; fi
