jobs:
  JOB-code-validation:
  name: Check code
  runs-on: ubuntu-latest
  timeout-minutes: 5
  steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ./.flutter
        key: flutter-${{ runner.os }}-${{ github.repository }}-${{ env.FLUTTER_VERSION }}-${{ env.CACHE_VERSION }}

    - name: Install-flutter-ci
      run: ./run install-ci-flutter

    - name: Check flutter version
      run: flutter --version

    - name: Check code format
      run: dart format .

    - name: Check code syntax and logic is correct
      run: ./run lint

    - name: Check code passes unit tests.
      run: ./run test