name: Nepali Calander Staging Workflow
on:
  push:
    branches:
      - feat_1/github_actions

env:
  FLUTTER_VERSION: 3.19.2
  CACHE_VERSION: 2024_04_11
  FLUTTER_PATH: .flutter

jobs:
  JOB-code-validation:
    name: Check code
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      # Cahce flutter sdk
      - uses: actions/cache@v4
        with:
          # Do not wrap ./.flutter with double quotes because in the next workflow, it won't be able to use the cache.
          path: ./.flutter
          key: flutter-${{ runner.os }}-${{ github.repository }}-${{ env.FLUTTER_VERSION }}-${{ env.CACHE_VERSION }}

      - name: Install flutter SDK
        run: ./run install-ci-flutter

      - name: Show flutter current versions
        run: flutter --version

      - name: Check code format
        run: dart format .

      - name: Check code synatx and logic is correct
        run: ./run lint

      - name: Check code passes unit tests
        run: ./run test

  JOB-build-android-to-artifact:
    name: Convert android build to artifact
    needs: JOB-code-validation
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          # Do not wrap ./.flutter with double quotes because in the next workflow, it won't be able to use the cache.
          path: ./.flutter
          key: flutter-${{ runner.os }}-${{ github.repository }}-${{ env.FLUTTER_VERSION }}-${{ env.CACHE_VERSION }}

      - name: Install flutter SDK
        run: ./run install-ci-flutter

      - name: Show flutter current versions
        run: flutter --version

      - name: Get android code signing files
        run: |
          ./appsign add-android-debugkey
          ls -alh *.jks

      - name: Build android apk file
        run: |
          ./run build-apk
          ./appsign remove-android-key

      # - name: Show generated version
      #   run: |
      #     export $EM_VERSION=$( ./run android-version build/app/outputs/flutter-apk/app-staging-release.apk all)
      #     echo "App version is: $EM_VERSION"

      - name: Save anroid artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-result
          path: |
            build/app/outputs/flutter-apk/app-staging-release.apk

