name: Nepali Calander Staging Workflow
on:
  push:
    branches:
      - feat_1/github_actions

env:
  FLUTTER_VERSION: 3.19.2
  CACHE_VERSION: 2024_04_11
  FLUTTER_PATH: .flutter

jobs:
  JOB-code-validation:
    name: Check code
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      # Cahce flutter sdk
      - uses: actions/cache@v4
        with:
          # Do not wrap ./.flutter with double quotes because in the next workflow, it won't be able to use the cache.
          path: ./.flutter
          key: flutter-${{ runner.os }}-${{ github.repository }}-${{ env.FLUTTER_VERSION }}-${{ env.CACHE_VERSION }}

      - name: Install flutter SDK
        run: ./run install-ci-flutter

      - name: Show flutter current versions
        run: flutter --version

      - name: Check code format
        run: dart format .

      - name: Check code synatx and logic is correct
        run: ./run lint

      - name: Check code passes unit tests
        run: ./run test

  JOB-build-android-to-artifact:
    name: Convert android build to artifact
    needs: JOB-code-validation
    runs-on: ubuntu-latest
    timeout-minutes: 25
    # Environment specific to this job.
    env:
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_UPLOAD_KEY_BASE64: ${{ secrets.ANDROID_UPLOAD_KEY_BASE64 }}
      SECRETS_PASSWORD: ${{ secrets.SECRETS_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          # Do not wrap ./.flutter with double quotes because in the next workflow, it won't be able to use the cache.
          path: ./.flutter
          key: flutter-${{ runner.os }}-${{ github.repository }}-${{ env.FLUTTER_VERSION }}-${{ env.CACHE_VERSION }}

      - name: Install flutter SDK
        run: ./run install-ci-flutter

      - name: Show flutter current versions
        run: flutter --version

      - name: Build android apk file
        run: ./run build-apk

      - name: Save anroid artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-result
          path: |
            build/app/outputs/flutter-apk/app-debug.apk

